### ISSUE TITLE
Cannot pass data from datapreview to charts

### ISSUE THREAD

**Issue by riyu94** [gbrian/grafana-echart-panel#1]
Hi,

I tried with a simple query on pie chart and pasted the pie echart code on the chart section. Can see data in data preview and tried to replace some code in chart, still doesn't work.
It would be great if you could provide some steps or a way to pass data from data preview to charts.
Thank you.

**Comment by gbrian** [comment]
@riyu94 ,
Hi, thanks for testing. Sorry still draft version so did not work too much on the readme, my fault.
I'll be working on a "demo" dashboard. In the meanwhile hope this will help:

```
option = {
    tooltip : {
        formatter: "{a} <br/>{b} : {c}%"
    },
    toolbox: {
        feature: {
            restore: {},
            saveAsImage: {}
        }
    },
    series: [
        {
            min: parseInt( data.series[0].stats.min ),
            max: parseInt( data.series[0].stats.max ),
            name: '业务指标',
            type: 'gauge',
            detail: {formatter:'{value}%'},
            data: [{value: parseInt( data.series[0].stats.avg ), name: '完成率'}]
        }
    ]
};

```
Check on `Data preview` the JSON graph.

**Comment by riyu94** [comment]
Yay, it works!!!
Thank you for helping :)
