### ISSUE TITLE
Echart Panel not working as expected on Grafana v 6.x

### ISSUE THREAD

**Issue by Vishawjeet** [gbrian/grafana-echart-panel#10]
As per git hub images, we can use different type of e chart visualization. But when I use this plugin. I am only getting line graph only. Can you help me out, how we can change this. There are diffrent textboxes for HTML,JS etc.,  But all are not editable. 
![image](https://user-images.githubusercontent.com/5374908/59090062-4ffa9f00-8929-11e9-9e6b-627f1b5419e3.png)

![image](https://user-images.githubusercontent.com/5374908/59090088-630d6f00-8929-11e9-8613-0ab1cb1bb06b.png)

![image](https://user-images.githubusercontent.com/5374908/59090106-728cb800-8929-11e9-8f51-489e580bad35.png)

![image](https://user-images.githubusercontent.com/5374908/59090120-80dad400-8929-11e9-82e0-456f26580131.png)

Nothing seems to be editable.

I am using Grafana v 6.x

**Comment by gbrian** [comment]
@Vishawjeet sorry currently Grafana 6 is not supported due to a big refactor done by Grafana on their plugins "SDK" Any updates on this will be post on issue https://github.com/gbrian/grafana-echart-panel/issues/9
Sadly I have no time to fix it.
