### ISSUE TITLE
Export option in charts

### ISSUE THREAD

**Issue by riyu94** [gbrian/grafana-echart-panel#2]
Hi,

One enhancement suggestion would be to add excel export option, which is by default in other grafana panels.

Would be great if we could include that. Else charts seem to work well :)

**Comment by gbrian** [comment]
HI @riyu94 ,
I've never used that functionality sorry have no idea was there 😮 
Echarts has the `toolbox` , there's an option to see the data, will be that enough?
https://ecomfe.github.io/echarts-doc/public/en/option.html#toolbox.feature.dataView

BTW where I can find this option on the current Grafana panels?

**Comment by riyu94** [comment]
Hi gbrian,

I have attached a picture with that functionality in grafana charts.
The toolbox in echarts is only offering saveAsPng only. Saving it as excel is really useful.
![capture](https://user-images.githubusercontent.com/21206708/49249051-2556e900-f3d0-11e8-80b7-bcc0e994eea9.PNG)

**Comment by gbrian** [comment]
@riyu94 great, asked for help: https://community.grafana.com/t/export-csv-data/2233?u=gbrian

**Comment by riyu94** [comment]
Hi @gbrian, I just checked the grafana reply on our export question, they have provided some solution!
Can we try that?
https://community.grafana.com/t/export-csv-data/2233/7

**Comment by gbrian** [comment]
@riyu94 sorry for late respone.
There you go: https://github.com/gbrian/grafana-echart-panel/commit/78c57df51b9856f8e4c58c2f1a75bcdf84cc4ca8

BUT...there's always a BUT 🤓 
need you to move to branch "ver2" and help me testing new version 😉 

![image](https://user-images.githubusercontent.com/767180/51503715-e5fbb600-1ddc-11e9-8f4b-024ca136cae0.png)

**Comment by riyu94** [comment]
Yayyyyy @gbrian, sure thing!!! will this version work with the new some latest grafana versions?

**Comment by gbrian** [comment]
@riyu94 not sure about what you mean, sorry 😔 but was developed using latest grafana...so hope is working fine. Sorry won't be backward compatible but I'm sure you'll find it easiest than initial prototype, I apologize for the inconvineces when moving to new versions 😅 
Please don't hesitate...well you know 😆

**Comment by riyu94** [comment]
@gbrian Answers my question, wanted it to work with latest grafana. Sounds good 💯. Surely, won't hesitate 💃

**Comment by riyu94** [comment]
Hi @gbrian, I tried with earlier grafana and latest grafana 5.4.3, both not showing the export options :( Is it specific with certain charts or Am I doing something wrong?
![image](https://user-images.githubusercontent.com/21206708/51507203-aadd9080-1da4-11e9-9221-b3f7d756bb3e.png)
![image](https://user-images.githubusercontent.com/21206708/51507226-c47ed800-1da4-11e9-8178-40f8de620573.png)

**Comment by riyu94** [comment]
hi @gbrian, just noticed that the feature 'excel export' is not showing up in the html code.
![image](https://user-images.githubusercontent.com/21206708/51514706-bab99c80-1dc5-11e9-8657-b6b1a13d733d.png)

**Comment by gbrian** [comment]
@riyu94 ok, I'll ask @daniellee for help never used those options but should be similar to CSV. Back to you asap

**Comment by gbrian** [comment]
@riyu94 dammit, turning crazy forgot to push "dist" folder content as got some projects where are exlcuded (🙄 kind of exccuse here) Pushed be sure to be at branch ver2: https://github.com/gbrian/grafana-echart-panel/commit/91c49aca52d8fa32bec22034a91f432407dd3e88

**Comment by riyu94** [comment]
It works!!!! Thank you :) @gbrian

**Comment by gbrian** [comment]
Great @riyu94, keep me posted!
