### ISSUE TITLE
[Feature Request] Resize ECharts when panel size changes

### ISSUE THREAD

**Issue by Ovilia** [gbrian/grafana-echart-panel#5]
Hi. Thanks for making this plugin.

I wonder if there is a way to detect panel size change (may cause by dragging panel span, or resizing Browser window) and resize ECharts?

I found [this post](https://community.grafana.com/t/panel-developping-how-to-detect-panel-resize/4007/4) and I think it should be done inside `src/controller.js`. And I'm not sure if this works for Browser window resizing.

Could you please provide this feature if it's not available right now?
Thanks!

**Comment by gbrian** [comment]
Ouch @Ovilia just saw this 😔 isn't the resize done automatically? I had no issues with this but if you still having the problem please tell me more info about. If not I'll close this

**Comment by Ovilia** [comment]
I'm using the `HTML` panel to make charts. I guess that's why. I'll try with the option panel later. Thanks!
