### ISSUE TITLE
sory, i don't know how to use this panel,someone who can help me out?

### ISSUE THREAD

**Issue by maicb** [gbrian/grafana-echart-panel#6]
sory, i don't know how to use this panel,someone who can help me out?

**Comment by maicb** [comment]
> 嗨@maicb，
> 我的错，试试看
> 
> ## 基本的echart
> * 添加新的echart面板
> * 将此json粘贴到“ _图表”_选项卡上
> 
> ```
>  {
>     xAxis: {
>         type: 'category',
>         data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
>     },
>     yAxis: {
>         type: 'value'
>     },
>     series: [{
>         data: [820, 932, 901, 934, 1290, 1330, 1320],
>         type: 'line'
>     }]
> };
> ```
> 这将绘制折线图。
> 
> ## 连接您的数据
> * 使用grafana演示数据源添加新指标
> * 查看“ _数据预览”_选项卡
> * 现在使用特殊的变量调用* data *更新你的echart json，如下所示：
>   更改：
> 
> ```
> data: [820, 932, 901, 934, 1290, 1330, 1320],
> ```
> 这样
> 
> ```
> data:data.series[0].datapoints.map(p => p[0]),
> ```
> 这将使用第一个指标中的值
> 
> 更多示例：[https](https://ecomfe.github.io/echarts-examples/public/index.html)：[//ecomfe.github.io/echarts-examples/public/index.html](https://ecomfe.github.io/echarts-examples/public/index.html)
> 
> 一个新的简化版即将推出，感谢您的测试。
![image](https://user-images.githubusercontent.com/39255780/50388942-101a7380-075e-11e9-987d-abe241e352f8.png)
thank you for your reply,but  when  i do like this,it is not work yet?i am not sure we use the panel is same or not?

**Comment by maicb** [comment]
> he values from the first metric

thank you ,i should use the default value in the html tab.

**Comment by Ovilia** [comment]
@gbrian What if there is some logic needs to be done before getting the option like: https://gallery.echartsjs.com/editor.html?c=x2aQj4yWVb

**Comment by KrishnaPG** [comment]
BTW, if someone needs to show time-series data (such as this: https://ecomfe.github.io/echarts-examples/public/editor.html?c=dynamic-data2 ), then Grafana already gives a compatible format data in the form of 'flotpairs' (and hence no need for mapping individual data points additionally). For example, 
````
 {
    xAxis: {
        type: 'time',
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: data.series[0].flotpairs,
        type: 'line'
    }]
};
````

**Comment by gbrian** [comment]
Great @KrishnaPG!
@Ovilia Currently you can define and invoke an anonymous function like this:

````
(function(){
   // Do your job here
   options = {};
   return options;
})()
````
In brief will push latest version that will return clearly define a function returning a value or a Promise.
Thanks for your comments!

**Comment by gbrian** [comment]
Just pushed ver2 branch in order to test
https://github.com/gbrian/grafana-echart-panel/tree/ver02
Will update README with the new changes

![image](https://user-images.githubusercontent.com/767180/51502566-d7120500-1dd6-11e9-8066-c9068cc92614.png)


@Ovilia this is the new way to define options:
 - Now you can return a Promise
![image](https://user-images.githubusercontent.com/767180/51502426-61a63480-1dd6-11e9-9e2b-8631759f6d3c.png)

HTML, JS and CSS are separated tabs
![image](https://user-images.githubusercontent.com/767180/51502483-9fa35880-1dd6-11e9-8c5c-6e5a4593c136.png)

**Comment by Ovilia** [comment]
If I want to render chart instead of showing "no data" when the data is undefined, it is possible? For example, I may want to display a pie chart with 100% red area when no data. How to do this? @gbrian

**Comment by gbrian** [comment]
Hi @Ovilia,
Probably I'll do all custom html from the event handlers available at JS tab. Probably switching to static html when no data available.

**Comment by Ovilia** [comment]
But what if I want to use the option for no-data, not making any difference when there's data?
Any method to do this?

**Comment by gbrian** [comment]
Sorry, missed your question. Now I understand. Last habdler at JS tab receives data parameter with the "data" object to be passed to echart. From there you can check if its empty and "add" your fake data to make the echart render as expected. Ill send you an example asap.

**Comment by gbrian** [comment]
@Ovilia ,

A simple way to achive what you are looking for is to pass a fixed series to the echart when coming data is empty.
In this examples we use the "parsed" collection from the "data" parameter, in case is empty- no data-, we use a fixed value.
So chart will render in two different if there's data or not:
![image](https://user-images.githubusercontent.com/767180/53004514-a4891580-3431-11e9-94ce-f41ef402de6a.png)
![image](https://user-images.githubusercontent.com/767180/53004558-b8cd1280-3431-11e9-8fc0-291e57667dc4.png)


```
function getOptions(data, asset) {
                console.log(data)
                var series = [{value:100, name:'No data found', itemStyle:{ color: 'red'}}];
                if(data.parsed.length){
                  series = data.parsed
                            .map(p => ({value: p.data, 
                                      name: p.name, 
                                      itemStyle:{ color: p.color}
                            }));
                }
                /**
                 * data: Same as tab "Data". Can be process by event 'data-changed'
                 * asset: Access to echart utils to load resources 
                 */
                var options = option = {
                    backgroundColor: 'transparent',
                      tooltip: {
                          trigger: 'item',
                          formatter: "{a} <br/>{b}: {c} ({d}%)"
                      },
                      series: [
                          {
                              name:'访问来源',
                              type:'pie',
                              radius: ['50%', '70%'],
                              avoidLabelOverlap: false,
                              label: {
                                  normal: {
                                      show: false,
                                      position: 'center'
                                  },
                                  emphasis: {
                                      show: true,
                                      textStyle: {
                                          fontSize: '30',
                                          fontWeight: 'bold'
                                      }
                                  }
                              },
                              labelLine: {
                                  normal: {
                                      show: false
                                  }
                              },
                              data:series
                          }
                      ]
                  };
                // Return options
                return options;
                // Or promise: return new Promise((res, rej) => res(options));
            }
```

**Comment by Ovilia** [comment]
Thanks! Where exactly should I put the getOption function, and can it be accessed in Chart panel?

**Comment by gbrian** [comment]
This is from ver02 branch, just merged.
This is how it looks now:
![image](https://user-images.githubusercontent.com/767180/53102525-252c3c80-352c-11e9-9b0a-f780b86ef376.png)

HTML, JS and CSS has been separated on different tabs
EChart Options: contains a function returning an object or promise.

**Currently master branch has latest changes.**

**Comment by Ovilia** [comment]
Thanks!

**Comment by gbrian** [comment]
Welcome, I'll be super happy if you can share some screenshots from your work :D

**Comment by gbrian** [comment]
Hi @Ovilia I'm closing this issue, feel free to re-open at anytime.
BTW I'll be supper happy on see your work 😄

**Comment by Ovilia** [comment]
@gbrian Thanks! But it's internal work so I'm afraid I cannot share with you. Maybe next time! :)
